version: '3'
services:
  vaporgolf-app:
    depends_on:
      - postgres
    build: .

    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432

  postgres:
    image: "postgres"
    environment:
      - POSTGRES_DB=vaporgolf-test
      - POSTGRES_USER=vaporgolf 
      - POSTGRES_PASSWORD=password
